import { Router } from "express";
import { authenticate } from "../../middlewares/auth";
import * as ctrl from "./tasks.controller";
const router = Router();
router.use(authenticate);
router.get("/", ctrl.list);
router.get("/all", ctrl.all);
router.post("/", ctrl.create);
router.patch("/:id", ctrl.update);
router.delete("/:id", ctrl.remove);
export default router;
